# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BSBDJ' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BSBDJ


pod 'AFNetworking', '~> 3.1.0'
pod 'MJExtension', '~> 3.0.13'
pod 'SDWebImage', '~> 3.8.2'
pod 'SVProgressHUD', '~> 2.0.4'
pod 'MJRefresh', '~> 3.1.12'
end
